# Generated by Django 2.0.5 on 2018-07-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0027_auto_20180709_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('idFacturacion', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('nFactura', models.PositiveSmallIntegerField(error_messages={'unique': 'Ya existe este número de factura.'}, unique=True, verbose_name='N° de factura')),
                ('fecha_facturacion', models.DateField(verbose_name='Fecha de facturación')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto')),
                ('pago', models.PositiveIntegerField(verbose_name='Pago')),
                ('plazo', models.PositiveSmallIntegerField(verbose_name='Plazo')),
                ('Activacion', models.ForeignKey(null=True, on_delete=models.SET(None), related_name='Facturas', to='Eventos.Activaciones', verbose_name='Activacion')),
            ],
            options={
                'ordering': ['-nFactura', '-Activacion'],
            },
        ),
        migrations.AlterField(
            model_name='contactos',
            name='Cliente',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='Contactos', to='Eventos.Clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='errores',
            name='Evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), related_name='Errores', to='Eventos.Eventos', verbose_name='Evento'),
        ),
    ]
